### ISSUE TITLE
Generate API client credentials

### ISSUE THREAD

**Issue by jammehcow** [pubby-club/pubby.club#22]
**Is your feature request related to a problem? Please describe.**
The authorization modal on the API give a choice of either password-based login or client-ide/secret login. Currently both are unable to be used as there's no obvious way to generate a client secret/id (even the user login requires this).

**Describe the solution you'd like**
A panel in the user settings to generate client credentials would be sufficient.

**Describe alternatives you've considered**
I've attempted to figure out how the login page gets a token. It seems to just pass a literal token to the `/token` endpoint along with the username and password. Can't figure out how to pass that to the swagger API page, but could be used(if the token is static) in an application.

**Additional context**
I'm specifically working on Twitch integration where a chat command can receive the currently playing song of a given room. This is next to impossible as API calls are locked down.

**Comment by salomaosnff** [comment]
Hi @jammehcow, I apologize for the delay in responding.

Integration with other sites is not yet fully ready.
If you want, you can message me on discord to talk about it and then maybe I can release a client_id and secret for you to try our API and report bugs.
